### ISSUE TITLE
Typo in DataExtension Verion

### ISSUE THREAD

**Issue by attilah** [email360/ssjs-lib#7]
Thanks for this library, it looks really useful to simplify the code needs to be written.

While looking at the setup page I found that there is a missing `s` in `DataExtension Verion` in `setup.ssjs`.

Question: Where can the test files be found? I'd be interested in your testing method of SSJS code.

**Comment by shdinx** [comment]
Hey @attilah 

thank you for pointing this out. This is a consistent typo and the tests did not fail because of that. I am working on a major new release which will be launched early next year and this typo will be fixed.

In general I use Sonar for general purpose and to test individual elements I use Cypress. These files and setup are not publicly available but happy to share approaches and discuss options.

**Comment by attilah** [comment]
@shdinx  I'd be definitely interested in your testing approach, can you shot me a DM on twitter or you'd like to discuss it here?
